name: Get Changed Files
description: Get all of the files changed/modified in a pull request or push's commits.
author: HanseltimeIndustries
branding:
  icon: file
  color: purple
runs:
  using: node12
  main: bundle/index.js
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
  format:
    description: >
      Format of the steps output context.
      Can be 'space-delimited', 'csv', or 'json'.
    required: true
    default: space-delimited
  filter:
    description: >
      A csv string of minimatch globs that will filter out the file changes.
      This is a short cut for returning changed files in a specific folder.
    required: false
outputs:
  all:
    description: >
      Array of all changed files.
  added:
    description: >
      Array of added files.
  modified:
    description: >
      Array of modified files.
  removed:
    description: >
      Array of removed files.
  renamed:
    description: >
      Array of renamed files.
  added_modified:
    description: >
      Array of all added and modified files.
  # For backwards-compatibility
  deleted:
    description: >
      Array of deleted files.
