name: Tests
on:
  workflow_call:
    inputs:
      from:
        required: true
        type: string
      templatePrefix:
        required: true
        type: string

# This will cancel in progress jobs if another job with the same ref gets started.
# Github run_id is a backup in case github.ref doesn't exist for some reason
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      # TODO: caching this action would accelerate the run
      - name: corepack
        run: |
          corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: install
        run: |
          npm ci
      - name: commit-linting
        run: |
          if [[ "${{ github.base_ref }}" != "" ]]; then
            echo "Setting up git environment for commitlint of pull request"
            git fetch origin ${{ github.base_ref }}
            git fetch ${{ github.event.pull_request.head.repo.clone_url }} ${{ github.head_ref }}
            npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
          else
            echo "Setting up git environment for commitlint of branch push"
            git fetch origin ${{ github.ref_name }} --unshallow
            # We limit to this commit since the earlier commits weren't being linted
            npx commitlint --from 5b2bd81ef9363f80b8875e82e77cfad764d53b27
          fi
      - name: build
        run: |
          npm run build
      - name: linting
        run: |
          npm run lint
          npm run format
      - name: testing
        run: |
          npm run test
      - name: bundle
        run: |
          npm run bundle

  int-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: corepack
        run: |
          corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: install
        run: |
          npm ci
      - name: bundle
        run: |
          npm run bundle

      - id: files
        name: Run the action
        uses: ./

      # TODO: caching this action would accelerate the run
      - name: Print steps context output
        run: |
          echo 'steps.files.outputs.all=${{ steps.files.outputs.all }}'
          echo 'steps.files.outputs.added=${{ steps.files.outputs.added }}'
          echo 'steps.files.outputs.modified=${{ steps.files.outputs.modified }}'
          echo 'steps.files.outputs.removed=${{ steps.files.outputs.removed }}'
          echo 'steps.files.outputs.renamed=${{ steps.files.outputs.renamed }}'
          echo 'steps.files.outputs.added_modified=${{ steps.files.outputs.added_modified }}'

  no-committed-bundle:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref }}
    steps:
      - id: bundle-changed-files
        name: Run the action
        uses: hanseltimeindustries/get-changed-files@v1
        with:
          format: 'space-delimited'
          filter: "bundle/**/*"

      - name: No committed bundle
        if: ${{ steps.bundle-changed-files.outputs.all }}
        shell: bash
        run: |
          echo "all files in bundle/ directory are committed by the release process.  Please make sure not to commit your bundle files!"
          exit 1
